Repository f-lab-edu/heeverse-ticket, pull requests merged in 2023-11, with the labels that each got.

#104 Lock전용 DataSource 분리
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/com/heeverse/common/Constants.java
  src/main/java/com/heeverse/common/DataSourceMonitoring.java
  src/main/java/com/heeverse/config/LockSqlSessionFactoryConfiguration.java
  src/main/java/com/heeverse/config/MultiDataSource.java
  src/main/java/com/heeverse/config/RdsConnectionProps.java
  src/main/java/com/heeverse/config/SqlSessionFactoryConfiguration.java
  src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
  src/main/resources/application-dev-test.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/mapper/basic/ConcertMapper.xml
  src/main/resources/mapper/basic/GradeTicketMapper.xml
  src/main/resources/mapper/basic/MemberMapper.xml
  src/main/resources/mapper/basic/TicketOrderAggregationtMapper.xml
  src/main/resources/mapper/basic/TicketOrderLogMapper.xml
  src/main/resources/mapper/basic/TicketOrderMapper.xml
  src/main/resources/mapper/lock-mapper/TicketMapper.xml
  src/main/resources/mybatis-config.xml
  src/test/java/com/heeverse/HeeverseTicketApplicationTests.java
  src/test/java/com/heeverse/ticket/service/TicketIntegrationTest.java
Labels: chore, :recycle: refactor

#94 feat : 집계 기능 - 멀티스레드 버전
  src/main/java/com/heeverse/common/util/MultiThreadUtils.java
  src/main/java/com/heeverse/common/util/PaginationProvider.java
  src/main/java/com/heeverse/common/util/PrimitiveUtils.java
  src/main/java/com/heeverse/common/util/TicketUtils.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/AggregateDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/enums/StrategyType.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateInsertMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrderLog.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderAggregationMapper.java
  src/main/java/com/heeverse/ticket_order/service/AsynchronizableAggregation.java
  src/main/java/com/heeverse/ticket_order/service/MultithreadingAggregationService.java
  src/main/java/com/heeverse/ticket_order/service/QueryAggregationService.java
  src/main/java/com/heeverse/ticket_order/service/SynchronizableAggregation.java
  src/main/java/com/heeverse/ticket_order/service/reader/AggregationReader.java
  src/main/java/com/heeverse/ticket_order/service/reader/CommonAggregationReader.java
  src/main/java/com/heeverse/ticket_order/service/reader/StreamHelper.java
  src/main/java/com/heeverse/ticket_order/service/reader/TicketAggrFacade.java
  src/main/java/com/heeverse/ticket_order/service/reader/firstclass/GradeInfo.java
  src/main/java/com/heeverse/ticket_order/service/reader/firstclass/ResultConcurrentMap.java
  src/main/java/com/heeverse/ticket_order/service/reader/firstclass/ResultHashMap.java
  src/main/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMap.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/AggregationJobWrapper.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/AggregationStrategy.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/MultithreadingStrategy.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/SingleThreadStrategy.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/StreamAggregationStrategy.java
  src/main/java/com/heeverse/ticket_order/service/reader/subscriber/AggregateSubscriber.java
  src/main/java/com/heeverse/ticket_order/service/reader/subscriber/Subscriber.java
  src/main/java/com/heeverse/ticket_order/service/reader/subscriber/TaskMessage.java
  src/main/resources/logback-spring.xml
  src/main/resources/mapper/basic/TicketOrderAggregationtMapper.xml
  src/main/resources/mapper/basic/TicketOrderLogMapper.xml
  src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
  src/test/java/com/heeverse/ticket_order/service/MultithreadingAggregationServiceUnitTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderIntegrationTest_aggregation.java
  src/test/java/com/heeverse/ticket_order/service/reader/AggregationReaderTest.java
  src/test/java/com/heeverse/ticket_order/service/reader/PaginationProviderTest.java
  src/test/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMapTest.java
Labels: :sparkles: enhancement, 티켓, 예매

#109 [#108] 티켓 집계 리팩토링
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  .github/workflows/pr-request.yml
  build.gradle
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/AggregateDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/StrategyDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/enums/StrategyType.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrderLog.java
  src/main/java/com/heeverse/ticket_order/service/AsynchronizableAggregation.java
  src/main/java/com/heeverse/ticket_order/service/MultithreadingAggregationService.java
  src/main/java/com/heeverse/ticket_order/service/QueryAggregationService.java
  src/main/java/com/heeverse/ticket_order/service/SynchronizableAggregation.java
  src/main/java/com/heeverse/ticket_order/service/reader/CommonAggregationReader.java
  src/main/java/com/heeverse/ticket_order/service/reader/QueryAggregationReader.java
  src/main/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMap.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/AggregationStrategy.java
  src/main/java/com/heeverse/ticket_order/service/reader/strategy/StreamAggregationStrategy.java
  src/main/resources/mapper/basic/TicketOrderLogMapper.xml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/common/factory/TicketLogFactory.java
  src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
  src/test/java/com/heeverse/docs/TicketDocsResultFactory.java
  src/test/java/com/heeverse/ticket_order/service/MultithreadingAggregationServiceUnitTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderIntegrationTest_aggregation.java
  src/test/java/com/heeverse/ticket_order/service/reader/AggregationReaderTest.java
  src/test/java/com/heeverse/ticket_order/service/reader/PaginationProviderTest.java
  src/test/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMapTest.java
  src/test/java/com/heeverse/ticket_order/service/reader/firstclass/ResultMapUnitTest.java
  src/test/java/com/heeverse/ticket_order/service/transfer/ResultTransferUnitTest.java
Labels: 티켓

#111 refactor : read commited로 수정
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/main/java/com/heeverse/common/DataSourceMonitoring.java
  src/main/java/com/heeverse/config/LockSqlSessionFactoryConfiguration.java
  src/main/java/com/heeverse/config/MultiDataSource.java
  src/main/java/com/heeverse/config/RdsConnectionProps.java
  src/main/java/com/heeverse/config/SqlSessionFactoryConfiguration.java
  src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
  src/main/java/com/heeverse/ticket/domain/mapper/TicketMapper.java
  src/main/java/com/heeverse/ticket/service/TicketService.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketOrderException.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
  src/main/resources/application-dev-test.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/mapper/ConcertMapper.xml
  src/main/resources/mapper/GradeTicketMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/TicketMapper.xml
  src/main/resources/mapper/TicketOrderAggregationtMapper.xml
  src/main/resources/mapper/TicketOrderLogMapper.xml
  src/main/resources/mapper/TicketOrderMapper.xml
  src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
Labels: :bug: bug
