Repository f-lab-edu/heeverse-ticket, pull requests merged in 2023-08, with the labels that each got.

#16 [#4] JWT token 발행 Provider 추가
  build.gradle
  src/main/java/com/heeverse/HeeverseTicketApplication.java
  src/main/java/com/heeverse/config/JsonAuthenticationFilter.java
  src/main/java/com/heeverse/config/SecurityConfig.java
  src/main/java/com/heeverse/member/service/MemberService.java
  src/main/java/com/heeverse/security/PwdEncoder.java
  src/main/java/security/JwtTokenProvider.java
  src/main/resources/application-local.yml
  src/test/java/com/heeverse/member/service/MemberServiceTest.java
Labels: enhancement

#19 [#4] 민감정보 처리 및 security redirect 이슈 해결
  build.gradle
  src/main/java/com/heeverse/common/Constants.java
  src/main/java/com/heeverse/common/DateAdapter.java
  src/main/java/com/heeverse/common/DateTarget.java
  src/main/java/com/heeverse/config/SecurityConfig.java
  src/main/java/com/heeverse/config/VaultEnvironmentConfig.java
  src/main/java/com/heeverse/security/Authority.java
  src/main/java/com/heeverse/security/JsonAuthenticationFilter.java
  src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
  src/main/java/com/heeverse/security/JwtTokenProvider.java
  src/main/java/com/heeverse/security/LoginAuthenticationProvider.java
  src/main/java/com/heeverse/security/exception/JwtParsingException.java
  src/main/java/com/heeverse/security/exception/VaultTokenNotExistException.java
  src/main/java/security/JwtTokenProvider.java
  src/main/resources/application-local.yml
  src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
Labels: refactor

#22 [#18] concert 도메인 생성
  src/main/java/com/heeverse/HeeverseTicketApplication.java
  src/main/java/com/heeverse/common/BaseEntity.java
  src/main/java/com/heeverse/common/Constants.java
  src/main/java/com/heeverse/common/DateTarget.java
  src/main/java/com/heeverse/concert/controller/ConcertController.java
  src/main/java/com/heeverse/concert/domain/FutureDate.java
  src/main/java/com/heeverse/concert/domain/FutureDateValidator.java
  src/main/java/com/heeverse/concert/domain/entity/Concert.java
  src/main/java/com/heeverse/concert/domain/mapper/ConcertMapper.java
  src/main/java/com/heeverse/concert/dto/ConcertRequestDto.java
  src/main/java/com/heeverse/concert/dto/ConcertResponseDto.java
  src/main/java/com/heeverse/concert/exception/ConcertTimeValidationException.java
  src/main/java/com/heeverse/concert/service/ConcertService.java
  src/main/java/com/heeverse/config/SecurityConfig.java
  src/main/java/com/heeverse/member/controller/MemberController.java
  src/main/java/com/heeverse/member/service/MemberService.java
  src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
  src/main/java/com/heeverse/security/JwtTokenProvider.java
  src/main/java/com/heeverse/ticket/domain/entity/GradeTicket.java
  src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
  src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
  src/main/java/com/heeverse/ticket/domain/mapper/GradeTicketMapper.java
  src/main/java/com/heeverse/ticket/domain/mapper/TicketMapper.java
  src/main/java/com/heeverse/ticket/dto/GradeTicketDto.java
  src/main/java/com/heeverse/ticket/dto/TicketGradeDto.java
  src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
  src/main/java/com/heeverse/venue/Venue.java
  src/main/resources/logback.xml
  src/main/resources/mapper/ConcertMapper.xml
  src/main/resources/mapper/GradeTicketMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/concert/controller/ConcertControllerTest.java
  src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
  src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
  src/test/java/com/heeverse/member/dto/RecordTypeTest.java
  src/test/java/com/heeverse/member/service/MemberServiceTest.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
  src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
Labels: enhancement, 공연

#21 [#17] 티켓 생성 기능
  src/main/java/com/heeverse/common/Delimiter.java
  src/main/java/com/heeverse/common/SerialNumber.java
  src/main/java/com/heeverse/common/SerialTokenDto.java
  src/main/java/com/heeverse/common/exception/SerialNumberException.java
  src/main/java/com/heeverse/common/util/StringUtils.java
  src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
  src/main/java/com/heeverse/ticket/domain/TicketSerialTokenDto.java
  src/main/java/com/heeverse/ticket/domain/entity/GradeTicket.java
  src/main/java/com/heeverse/ticket/domain/entity/OrderInfo.java
  src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
  src/main/java/com/heeverse/ticket/domain/entity/TicketGrade.java
  src/main/java/com/heeverse/ticket/domain/mapper/TicketMapper.java
  src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
  src/main/java/com/heeverse/ticket/exception/DuplicatedTicketException.java
  src/main/java/com/heeverse/ticket/service/TicketService.java
  src/main/resources/mapper/TicketMapper.xml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/common/AssertUtils.java
  src/test/java/com/heeverse/common/SerialNumberTest.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
  src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
  src/test/java/com/heeverse/ticket/service/TicketServiceTest.java
Labels: 티켓

#30 [#31] github-Action yml 파일 추가
  .github/workflows/deploy.yml
Labels: :bricks: Infra

#29 [#24] 공연목록을 조회한다.
  build.gradle
  src/main/java/com/heeverse/common/AbstractPaging.java
  src/main/java/com/heeverse/common/Paging.java
  src/main/java/com/heeverse/common/PagingRequest.java
  src/main/java/com/heeverse/common/Sorting.java
  src/main/java/com/heeverse/concert/controller/ConcertController.java
  src/main/java/com/heeverse/concert/domain/FutureDate.java
  src/main/java/com/heeverse/concert/domain/entity/Concert.java
  src/main/java/com/heeverse/concert/domain/mapper/ConcertMapper.java
  src/main/java/com/heeverse/concert/dto/ConcertResponseDto.java
  src/main/java/com/heeverse/concert/dto/persistence/ConcertRequestMapperDto.java
  src/main/java/com/heeverse/concert/dto/persistence/ConcertResponseMapperDto.java
  src/main/java/com/heeverse/concert/dto/presentation/ConcertRequestDto.java
  src/main/java/com/heeverse/concert/dto/presentation/SearchConcertRequestDto.java
  src/main/java/com/heeverse/concert/dto/presentation/SearchConcertResponseDto.java
  src/main/java/com/heeverse/concert/service/ConcertService.java
  src/main/java/com/heeverse/config/SecurityConfig.java
  src/main/java/com/heeverse/ticket/domain/TicketSerialNumber.java
  src/main/java/com/heeverse/ticket/domain/TicketSerialTokenDto.java
  src/main/java/com/heeverse/ticket/dto/TicketRequestDto.java
  src/main/resources/application-local.yml
  src/main/resources/logback.xml
  src/main/resources/mapper/ConcertMapper.xml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/HeeverseTicketApplicationTests.java
  src/test/java/com/heeverse/common/SerialNumberTest.java
  src/test/java/com/heeverse/concert/controller/ConcertControllerTest.java
  src/test/java/com/heeverse/concert/controller/ConcertIntegrationTest.java
  src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
  src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
  src/test/java/com/heeverse/ticket/service/TicketServiceTest.java
Labels: enhancement, 공연

#34 [#7] 회원가입, 로그인 통합테스트
  src/main/java/com/heeverse/config/RdsConnectionProps.java
  src/main/java/com/heeverse/member/domain/entity/Member.java
  src/main/resources/application-dev.yml
  src/main/resources/mapper/MemberMapper.xml
  src/test/java/com/heeverse/ControllerTestHelper.java
  src/test/java/com/heeverse/HeeverseTicketApplicationTests.java
  src/test/java/com/heeverse/member/MemberIntegrationTest.java
  src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
  src/test/java/com/heeverse/member/service/MemberServiceTest.java
Labels: refactor, 회원

#33 [#32] 공연, 티켓 테스트 코드 수정
  src/main/java/com/heeverse/concert/domain/entity/Concert.java
  src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
  src/main/java/com/heeverse/ticket/service/TicketService.java
  src/main/resources/application-local.yml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/common/SerialNumberTest.java
  src/test/java/com/heeverse/concert/ConcertRequestDtoFactory.java
  src/test/java/com/heeverse/concert/controller/ConcertIntegrationTest.java
  src/test/java/com/heeverse/concert/domain/entity/ConcertTest.java
  src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
  src/test/java/com/heeverse/member/controller/LoginAuthenticationTest.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketMapperTest.java
  src/test/java/com/heeverse/ticket/dto/TicketRequestDtoTest.java
  src/test/java/com/heeverse/ticket/service/TicketServiceTest.java
Labels: 공연, 티켓, refactor
