Repository f-lab-edu/heeverse-ticket, pull requests merged in 2023-10, with the labels that each got.

#67 [#61] script 문법 오류 수정
  script/ncpAddIp.sh
  script/ncpRemoveIp.sh
  script/runNcpApi.sh
Labels: :bricks: Infra

#68 [#61] cron 테스트
  .github/workflows/server-start-scheduler.yml
  .github/workflows/server-stop-scheduler.yml
Labels: :bricks: Infra

#69 [#61] cron 시간 UTC 기준 테스트
  .github/workflows/server-start-scheduler.yml
  .github/workflows/server-stop-scheduler.yml
Labels: :bricks: Infra

#70 fix : 워크플로우 수정
  .github/workflows/server-start-scheduler.yml
  .github/workflows/server-stop-scheduler.yml
Labels: :bricks: Infra

#53 [#36] 잔여 티켓 집계 기능 추가
  src/main/java/com/heeverse/ticket/domain/mapper/TicketMapper.java
  src/main/java/com/heeverse/ticket/service/TicketService.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsResponseDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketRemainsResponseMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketAggregationFailException.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
  src/main/resources/mapper/TicketMapper.xml
  src/test/java/com/heeverse/ticket/service/TicketIntegrationTest_aggregation.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderTestHelper.java
Labels: :sparkles: enhancement, 티켓, 예매

#44 [#36] 예매하기 기능 개발
  build.gradle
  src/main/java/com/heeverse/common/util/StringUtils.java
  src/main/java/com/heeverse/concert/controller/ConcertController.java
  src/main/java/com/heeverse/concert/domain/entity/Concert.java
  src/main/java/com/heeverse/concert/domain/mapper/ConcertMapper.java
  src/main/java/com/heeverse/concert/dto/persistence/RegisteredConcertMapperDto.java
  src/main/java/com/heeverse/concert/dto/presentation/RegisteredConcertResponseDto.java
  src/main/java/com/heeverse/concert/service/ConcertService.java
  src/main/java/com/heeverse/config/RdsConnectionProps.java
  src/main/java/com/heeverse/member/domain/mapper/MemberMapper.java
  src/main/java/com/heeverse/member/service/MemberService.java
  src/main/java/com/heeverse/ticket/domain/entity/GradeTicket.java
  src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
  src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
  src/main/java/com/heeverse/ticket/domain/mapper/TicketMapper.java
  src/main/java/com/heeverse/ticket/dto/persistence/TicketRequestMapperDto.java
  src/main/java/com/heeverse/ticket/service/TicketService.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketOrderRequestDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketOrderResponseDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsResponseDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketOrderRequestMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketOrderUpdateMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketRemainsResponseMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrder.java
  src/main/java/com/heeverse/ticket_order/domain/exception/AlreadyBookedTicketException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/LockOccupancyFailureException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketAggregationFailException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketNotNormallyUpdatedException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketingFailException.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderMapper.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/logback-spring.xml
  src/main/resources/mapper/ConcertMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/TicketMapper.xml
  src/main/resources/mapper/TicketOrderMapper.xml
  src/test/java/com/heeverse/common/IntegrationTestService.java
  src/test/java/com/heeverse/common/factory/ConcertFactory.java
  src/test/java/com/heeverse/common/factory/MemberFactory.java
  src/test/java/com/heeverse/common/factory/TicketFactory.java
  src/test/java/com/heeverse/concert/domain/entity/ConcertHelper.java
  src/test/java/com/heeverse/concert/domain/entity/ConcertTest.java
  src/test/java/com/heeverse/member/domain/MemberTestHelper.java
  src/test/java/com/heeverse/member/service/MemberIntegrationTestService.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketSerialNumberHelper.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
  src/test/java/com/heeverse/ticket/service/TicketIntegrationTestService.java
  src/test/java/com/heeverse/ticket/service/TicketIntegrationTest_aggregation.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderTestHelper.java
  src/test/resources/test-data/create-test-data.sql
  src/test/resources/test-data/delete-test-data.sql
Labels: :sparkles: enhancement, 예매

#72 AWS 배포 제거
  .github/workflows/image-deploy.yml
  build.gradle
  src/main/java/com/heeverse/common/util/StringUtils.java
  src/main/java/com/heeverse/concert/controller/ConcertController.java
  src/main/java/com/heeverse/concert/domain/entity/Concert.java
  src/main/java/com/heeverse/concert/domain/mapper/ConcertMapper.java
  src/main/java/com/heeverse/concert/dto/persistence/RegisteredConcertMapperDto.java
  src/main/java/com/heeverse/concert/dto/presentation/RegisteredConcertResponseDto.java
  src/main/java/com/heeverse/concert/service/ConcertService.java
  src/main/java/com/heeverse/config/RdsConnectionProps.java
  src/main/java/com/heeverse/member/domain/mapper/MemberMapper.java
  src/main/java/com/heeverse/member/service/MemberService.java
  src/main/java/com/heeverse/ticket/domain/entity/GradeTicket.java
  src/main/java/com/heeverse/ticket/domain/entity/Ticket.java
  src/main/java/com/heeverse/ticket/domain/enums/BookingStatus.java
  src/main/java/com/heeverse/ticket/domain/mapper/TicketMapper.java
  src/main/java/com/heeverse/ticket/dto/persistence/TicketRequestMapperDto.java
  src/main/java/com/heeverse/ticket/service/TicketService.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketOrderRequestDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketOrderResponseDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/TicketRemainsResponseDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketOrderRequestMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketOrderUpdateMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/TicketRemainsResponseMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrder.java
  src/main/java/com/heeverse/ticket_order/domain/exception/AlreadyBookedTicketException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/LockOccupancyFailureException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketAggregationFailException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketNotNormallyUpdatedException.java
  src/main/java/com/heeverse/ticket_order/domain/exception/TicketingFailException.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderMapper.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/logback-spring.xml
  src/main/resources/mapper/ConcertMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/TicketMapper.xml
  src/main/resources/mapper/TicketOrderMapper.xml
  src/test/java/com/heeverse/common/IntegrationTestService.java
  src/test/java/com/heeverse/common/factory/ConcertFactory.java
  src/test/java/com/heeverse/common/factory/MemberFactory.java
  src/test/java/com/heeverse/common/factory/TicketFactory.java
  src/test/java/com/heeverse/concert/domain/entity/ConcertHelper.java
  src/test/java/com/heeverse/concert/domain/entity/ConcertTest.java
  src/test/java/com/heeverse/member/domain/MemberTestHelper.java
  src/test/java/com/heeverse/member/service/MemberIntegrationTestService.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketSerialNumberHelper.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
  src/test/java/com/heeverse/ticket/service/TicketIntegrationTestService.java
  src/test/java/com/heeverse/ticket/service/TicketIntegrationTest_aggregation.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderConcurrencyTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderFacadeTest.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderTestHelper.java
  src/test/resources/test-data/create-test-data.sql
  src/test/resources/test-data/delete-test-data.sql
Labels: :bricks: Infra

#73 [#71] Response 타입 공통화 및 RSET API 규약 정의
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  .github/workflows/pr-request.yml
  .github/workflows/release-server-1.yml
  .github/workflows/release-server-2.yml
  .github/workflows/server-start-scheduler.yml
  .github/workflows/server-stop-scheduler.yml
  README.md
  build.gradle
  script/ncpAddIp.sh
  script/ncpRemoveIp.sh
  script/runNcpApi.sh
  src/docs/asciidoc/index.adoc
  src/main/java/com/heeverse/common/IndexController.java
  src/main/java/com/heeverse/common/exception/ErrorMessage.java
  src/main/java/com/heeverse/common/exception/ErrorResponse.java
  src/main/java/com/heeverse/common/exception/GlobalExceptionHandler.java
  src/main/java/com/heeverse/common/exception/SerialNumberException.java
  src/main/java/com/heeverse/common/util/HttpStatusUtil.java
  src/main/java/com/heeverse/common/util/RegexUtils.java
  src/main/java/com/heeverse/common/util/StringUtils.java
  src/main/java/com/heeverse/concert/controller/ConcertController.java
  src/main/java/com/heeverse/config/SecurityConfig.java
  src/main/java/com/heeverse/member/controller/MemberController.java
  src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/resources/logback-spring.xml
  src/test/java/com/heeverse/ControllerTestHelper.java
  src/test/java/com/heeverse/common/factory/WithCustomSecurityContextFactory.java
  src/test/java/com/heeverse/common/factory/WithMockMember.java
  src/test/java/com/heeverse/concert/domain/entity/ConcertHelper.java
  src/test/java/com/heeverse/docs/ApiDocumentUtils.java
  src/test/java/com/heeverse/docs/ConcertDocsResultFactory.java
  src/test/java/com/heeverse/docs/ControllerExceptionUnitTest.java
  src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
  src/test/java/com/heeverse/docs/MemberDocsResultFactory.java
  src/test/java/com/heeverse/docs/TicketDocsResultFactory.java
  src/test/java/com/heeverse/docs/WebMvcTestForRestDocs.java
  src/test/java/com/heeverse/member/MemberIntegrationTest.java
  src/test/java/com/heeverse/member/domain/MemberTestHelper.java
  src/test/java/com/heeverse/ticket/domain/mapper/TicketTestHelper.java
Labels: 공통

#80 [#78] 티켓예매 결과 집계 기능
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/docs/asciidoc/index.adoc
  src/main/java/com/heeverse/config/AsyncConfig.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/AggregateDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateInsertMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrderLog.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderAggregationMapper.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderLogMapper.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderMapper.java
  src/main/java/com/heeverse/ticket_order/service/AggregationService.java
  src/main/java/com/heeverse/ticket_order/service/QueryAggregationService.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
  src/main/java/com/heeverse/ticket_order/service/event/TicketOrderEvent.java
  src/main/java/com/heeverse/ticket_order/service/event/TicketOrderEventHandler.java
  src/main/java/com/heeverse/ticket_order/service/reader/QueryAggregationReader.java
  src/main/java/com/heeverse/ticket_order/service/transfer/ResultDBTransfer.java
  src/main/java/com/heeverse/ticket_order/service/transfer/ResultTransfer.java
  src/main/resources/application-dev-test.yml
  src/main/resources/logback-spring.xml
  src/main/resources/mapper/TicketOrderAggregationtMapper.xml
  src/main/resources/mapper/TicketOrderLogMapper.xml
  src/main/resources/mapper/TicketOrderMapper.xml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/ControllerTestHelper.java
  src/test/java/com/heeverse/common/factory/TicketLogFactory.java
  src/test/java/com/heeverse/common/factory/TicketOrderingDto.java
  src/test/java/com/heeverse/concert/controller/ConcertControllerTest.java
  src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
  src/test/java/com/heeverse/docs/ControllerExceptionUnitTest.java
  src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
  src/test/java/com/heeverse/docs/TicketDocsResultFactory.java
  src/test/java/com/heeverse/member/domain/MemberTestHelper.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderIntegrationTest_aggregation.java
  src/test/resources/test-data/delete-test-data.sql
Labels: :sparkles: enhancement, 티켓, 예매

#81 [#78] 배포
  .github/badges/branches.svg
  .github/badges/jacoco.svg
  src/docs/asciidoc/index.adoc
  src/main/java/com/heeverse/config/AsyncConfig.java
  src/main/java/com/heeverse/ticket_order/controller/TicketOrderController.java
  src/main/java/com/heeverse/ticket_order/domain/dto/AggregateDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateInsertMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/dto/persistence/AggregateSelectMapperDto.java
  src/main/java/com/heeverse/ticket_order/domain/entity/TicketOrderLog.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderAggregationMapper.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderLogMapper.java
  src/main/java/com/heeverse/ticket_order/domain/mapper/TicketOrderMapper.java
  src/main/java/com/heeverse/ticket_order/service/AggregationService.java
  src/main/java/com/heeverse/ticket_order/service/QueryAggregationService.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderFacade.java
  src/main/java/com/heeverse/ticket_order/service/TicketOrderService.java
  src/main/java/com/heeverse/ticket_order/service/event/TicketOrderEvent.java
  src/main/java/com/heeverse/ticket_order/service/event/TicketOrderEventHandler.java
  src/main/java/com/heeverse/ticket_order/service/reader/QueryAggregationReader.java
  src/main/java/com/heeverse/ticket_order/service/transfer/ResultDBTransfer.java
  src/main/java/com/heeverse/ticket_order/service/transfer/ResultTransfer.java
  src/main/resources/application-dev-test.yml
  src/main/resources/logback-spring.xml
  src/main/resources/mapper/TicketOrderAggregationtMapper.xml
  src/main/resources/mapper/TicketOrderLogMapper.xml
  src/main/resources/mapper/TicketOrderMapper.xml
  src/main/resources/schema.sql
  src/test/java/com/heeverse/ControllerTestHelper.java
  src/test/java/com/heeverse/common/factory/TicketLogFactory.java
  src/test/java/com/heeverse/common/factory/TicketOrderingDto.java
  src/test/java/com/heeverse/concert/controller/ConcertControllerTest.java
  src/test/java/com/heeverse/concert/dto/ConcertRequestDtoTest.java
  src/test/java/com/heeverse/docs/ControllerExceptionUnitTest.java
  src/test/java/com/heeverse/docs/ControllerResponseUnitTest.java
  src/test/java/com/heeverse/docs/TicketDocsResultFactory.java
  src/test/java/com/heeverse/member/domain/MemberTestHelper.java
  src/test/java/com/heeverse/ticket_order/service/TicketOrderIntegrationTest_aggregation.java
  src/test/resources/test-data/delete-test-data.sql
Labels: :sparkles: enhancement

#83 [#78]: 배포 (Scouter Datasource 모니터링 코드 추가)
  src/main/java/com/heeverse/common/DataSourceMonitoring.java
  src/main/java/com/heeverse/common/DataSourceMonitoringMBean.java
Labels: :bricks: Infra

#84 [배포] Scouter Datasource 모니터링 코드 추가 2
  src/main/java/com/heeverse/common/DataSourceMonitoring.java
Labels: :bricks: Infra

#96 refactor : vault 서버로 부터 한번만 읽도록 수정
  .github/badges/jacoco.svg
  src/main/java/com/heeverse/config/SecurityConfig.java
  src/main/java/com/heeverse/security/JwtAuthenticationFilter.java
Labels: :zap: 성능개선
